spring:
  application:
    name: weeklyReportManagement

  datasource:
    url: jdbc:mysql://localhost:3306/wrm_sisenco_db
    username: root
    password: <your password>

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/<Your_realms>

server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG
